### ISSUE TITLE
期待支持青龙面板

### ISSUE THREAD

**Issue by Shuai-S** [amchii/tg-signer#14]
期待支持青龙面板

**Comment by amchii** [comment]
`tg-signer`就是一个命令，配置好环境应该可以在任何面板上使用，查看README。

**Comment by 389377616** [comment]
> `tg-signer`就是一个命令，配置好环境应该可以在任何面板上使用，查看README。

那老哥能出个教程嘛，技术小白不会这些

**Comment by amchii** [comment]
@389377616 我现在不使用青龙面板，但是配置也很简单，首先你根据README配置好环境登录tg，退出即可。在你的面板上配置shell命令执行你想用的`tg-signer`功能即可，比如发送一条消息
`tg-signer send-text -- -10006758812 浇水`
