### ISSUE TITLE
收到消息多导致ID无法识别，签到失败

### ISSUE THREAD

**Issue by buptxdt** [amchii/tg-signer#15]
报错：<img width="572" alt="image" src="https://github.com/user-attachments/assets/f85e74d9-418a-465f-9309-75d92d4e6ee6">

收到的消息过多，latest_chat里的条目会被最新的覆盖掉，导致不活跃的聊天框无法通过ID识别，报以上错误，经过测试，手动在tg客户端内给出错的ID对应的聊天发送消息后不报错了。

个人感觉可以通过配置调整latest_chat的数量来修复该问题。

**Comment by amchii** [comment]
按理说只要是你运行tg-signer时打印出来的那些聊天id就可以。`tg-signer run`可以通过`-n`来配置运行时获取的聊天数量，默认是20，你可以设置大一点试试。

**Comment by buptxdt** [comment]
我试试，感谢指点。
