### ISSUE TITLE
Dockerfile问题

### ISSUE THREAD

**Issue by linrongda** [amchii/tg-signer#18]
所提供的Dockerfile是否正确？
我编译时会提示**找不到Dockerfile**，于是我按照之前的项目经历重新写了一份Dockerfile如下：

> FROM python:3.12-slim AS builder
WORKDIR /tg-signer
ADD . /tg-signer
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN pip install -U "tg-signer"
FROM python:3.12-slim
WORKDIR /tg-signer
COPY --from=builder /usr/local/bin /usr/local/bin
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /tg-signer /tg-signer

项目文件如下：

> tg-signer
├── Dockerfile
├──start.sh

如此配置之后能够正常编译和运行，签到也设置好了

**Comment by amchii** [comment]
> 找不到Dockerfile

在项目的`docker`目录下：https://github.com/amchii/tg-signer/blob/main/docker/CN.Dockerfile。

**Comment by linrongda** [comment]
> > 找不到Dockerfile
> 
> 在项目的`docker`目录下：https://github.com/amchii/tg-signer/blob/main/docker/CN.Dockerfile 。

我使用的是同目录下的Dockerfile，因为我的服务器在境外。另外我也使用过CN.Dockerfile，同样错误。

**Comment by linrongda** [comment]
好吧，我知道问题所在了，按照所给的命令，Dockerfile文件应该放在根目录。

**Comment by amchii** [comment]
可以根据报错搜索一下哈，这个不是Dockerfile的问题，或者把完整报错贴出来~

**Comment by linrongda** [comment]
根据你的Dockerfile构建出来的镜像会比我的大一些，希望我的Dockerfile能给点作用吧，谢谢回复
