### ISSUE TITLE
定时运行不起作用

### ISSUE THREAD

**Issue by chentao1006** [amchii/tg-signer#2]
设置好了，手动运行是OK的，但不会自动运行。有哪些排查方法？谢谢。

config.json：
{"chats": [{"chat_id": 7046429717, "sign_text": "/check"}], "sign_at": "10:00:00", "random_seconds": 0}

**Comment by amchii** [comment]
你的配置是每天10点运行签到一次，不会自动运行有没有可能是`tg-signer`没有保持在后台（通过`screen`, `docker`容器等）。运行信息也可以查看日志`tg-signer.log`

**Comment by chentao1006** [comment]
我是在 macOS 上使用，请问具体怎么操作可以保持后台运行？

**Comment by amchii** [comment]
`tg-signer`就是个普通的脚本任务，所以你可以自行去搜索下macOS怎么保持一个脚本后台运行以及开机自启。
