### ISSUE TITLE
期待docker版本

### ISSUE THREAD

**Issue by whitesharks** [amchii/tg-signer#9]
期待docker版本，不然环境太复杂了

**Comment by amchii** [comment]
其实没什么环境需要配置吧😶不过貌似有热心群众提供了docker部署参考：
https://linux.do/t/topic/91604/90

**Comment by amchii** [comment]
可以的哦，我就是对几个bot签到，要确保bot的chat_id在你登录时获取的会话列表里（tg-signer login）

**Comment by amchii** [comment]
添加了Dockerfile用于构建镜像
